version: '3.4'

services:
  noriginmedianoriginspatialnavigation:
    image: noriginmedianoriginspatialnavigation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 6000:6000
