version: '3.4'

services:
  noriginmedianoriginspatialnavigation:
    image: noriginmedianoriginspatialnavigation
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6000:6000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/index.js"]
